FROM maven:3.9.6-eclipse-temurin-17

RUN apt-get update && \
    apt-get install -y chromium chromium-driver && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml .
COPY src ./src

CMD ["mvn", "test"]